name: Sync Public to Private Repo

on:
  push:
    branches:   # This will trigger the action for any branch push
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Configure Git with PAT
        run: |
          git config --global user.name "thecirculartribe"
          git config --global user.email "thecirculartribeofficial@gmail.com"

      - name: Push all branches to private repository
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)  # Get the current branch name
          git remote add private https://thecirculartribe:${{ secrets.PAT_PRIVATE_REPO }}@github.com/thecirculartribe/circularbloglive.git
          git push private $CURRENT_BRANCH  # Push all branches to the private repo
        env:
          PAT_PRIVATE_REPO: ${{ secrets.PAT_PRIVATE_REPO }}