name: Sync Public to Private Repo

on:
  push:
    branches:
      - '**'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch the entire history

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push current branch to private repository
        run: |
          CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)  # Get the current branch name
          git remote add private https://thecirulartribe:${{ secrets.PAT_PRIVATE_REPO }}@github.com/thecirulartribe/circularbloglive.git
          git push private $CURRENT_BRANCH
        env:
          PAT_PRIVATE_REPO: ${{ secrets.PAT_PRIVATE_REPO }}
