name: Sync Public to Private Repo

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public repository
        uses: actions/checkout@v2

      - name: Push changes to private repository
        run: |
          git remote add private https://github.com/thecirulartribe/circularbloglive.git
          git config user.email "thecirculartribeofficial@gmail.com"
          git config user.name "thecirculartribe"
          git checkout feature-branch
          git add .
          git commit -m "chnages made"
          git push private feature-branch
        env:
          GITHUB_TOKEN: ${{ secrets.PRIVATE_ACCESS_TOKEN }}
